# Site settings
title: alecu
header-img: img/reflektor-full.jpg
email: alecu@protocultura.net
description: "Retrofuturismo con alecu"
baseurl: ""
url: "http://alecu.protocultura.net"
twitter_username: alecura
github_username:  alecu
linkedin_username:  alecura
launchpad_username:  alecu
#facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
